server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://awsajith.c6hsg00jd6yo.eu-north-1.rds.amazonaws.com:3306/library?useSSL=false&&serverTimezone=UTC
    username: admin
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#    jpa format
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true
      format_sql: true
